version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - setup_remote_docker

      - restore_cache:
          keys:
          - kt-vertx-blog-{{ checksum "build.gradle" }}

      - run: sh ./gradlew shadowJar

      - save_cache:
          paths:
            - ~/.gradle
          key: kt-vertx-blog-{{ checksum "build.gradle" }}

      - run: |
          TAG=$(echo 0.1.$CIRCLE_BUILD_NUM-$CIRCLE_BRANCH | tr / -)
          NAME=usmans/blog
          docker login -u $REPO_USER -p $REPO_PASS
          docker build -t $NAME:$TAG .
          if [ "${CIRCLE_BRANCH}" == "master" ];
            then docker tag $NAME:$TAG $NAME:latest;
          fi
          docker push $NAME