version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          keys:
          - kt-vertx-blog-{{ checksum "build.gradle" }}

      - run: sh ./gradlew clean shadowJar

      - save_cache:
          paths:
            - ~/.gradle
          key: kt-vertx-blog-{{ checksum "build.gradle" }}

      - add_ssh_keys:
                fingerprints:
                  - "1f:75:78:e8:e8:7e:07:75:c9:0e:f7:2b:06:8a:3d:35"
      - run: ssh-keyscan 212.47.244.29 >> ~/.ssh/known_hosts
      - run: scp ./build/libs/uzi-vertx-fat.jar root@212.47.244.29:./upload/
      - run: ssh -t root@212.47.244.29 "cd ./vertx-blog-scripts; sh  ./redeploy.sh"
